[phases.setup]
nixPkgs = ["nodejs", "chromium", "python3", "gcc"]

[phases.install]
cmds = ["cp -r node-api/* . && npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node --no-warnings index.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_DISABLE_DEV_SHM_USAGE = "true"
