[phases.setup]
nixPkgs = ["nodejs", "chromium", "python3", "gcc", "gcc-c++", "make"]

[phases.install]
cmds = ["cd node-api && npm install"]

[phases.build]
cmds = ["cd node-api && npm run build"]

[start]
cmd = "cd node-api && node --no-warnings index.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_DISABLE_DEV_SHM_USAGE = "true"
