version: '3.8'

services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
      args:
        - BUILD_TIME=${BUILD_TIME:-local}
    container_name: dashboard
    ports:
      - ${DASHBOARD_PORT:-4001}:${DASHBOARD_PORT:-4001}
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_URL=http://node-api:${API_PORT:-3000}
    depends_on:
      - api
    networks:
      - app-network-local
    restart: unless-stopped

  api:
    build:
      context: ./node-api
      dockerfile: Dockerfile.local
      args:
        - BUILD_TIME=${BUILD_TIME:-local}
    container_name: node-api
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}
    volumes:
      - ./node-api:/app
      - /app/node_modules
      - whatsapp_sessions:/app/.wwebjs_auth
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-whatsapp_db}
      - DB_PORT=${DB_PORT:-3306}
      - API_PORT=${API_PORT:-3000}
      - SESSION_SECRET=${SESSION_SECRET:-local_session_secret}
      - JWT_SECRET=${JWT_SECRET:-local_jwt_secret}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
      - ASSISTANT_URL=${ASSISTANT_URL:-http://host.docker.internal:5000}
      - MAX_CONCURRENT_CLIENTS=5
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_DISABLE_DEV_SHM_USAGE=true
      - NODE_OPTIONS=--max-old-space-size=1024
    shm_size: '512m'
    networks:
      - app-network-local
    restart: unless-stopped

networks:
  app-network-local:
    driver: bridge

volumes:
  whatsapp_sessions:
    driver: local