# GNU nano 6.2                                                                                                                                                                                                                                                                                                                                                                                   docker-compose.yml *                                                                                                                                                                                                                                                                                                                                                                                           
version: '3.8'

services:
  dashboard:
    image: registry.gitlab.com/airadms/whatsapp_services:frontend-production
    container_name: dashboard
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_URL=http://node-api:${API_PORT}
    depends_on:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  api:
    image: registry.gitlab.com/airadms/whatsapp_services:backend-production
    container_name: node-api
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - API_PORT=${API_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - ASSISTANT_URL=${ASSISTANT_URL}

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
